version: '3.8'

services:
  # MongoDB Database Service
  mongo:
    image: mongo:latest
    container_name: solveria-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: solveria
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - solveria-network

  # Backend Service (Node.js/Express)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: solveria-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: mongodb://admin:password123@mongo:27017/solveria?authSource=admin
      JWT_SECRET: your-jwt-secret-key-here
      CORS_ORIGIN: http://localhost:8080
    depends_on:
      - mongo
    volumes:
      - ./src/backend:/app/src/backend
      - ./uploads:/app/uploads
      - /app/node_modules
    networks:
      - solveria-network

  # Frontend Service (Static Files)
  frontend:
    image: nginx:alpine
    container_name: solveria-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src/frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - solveria-network

# Named Volumes
volumes:
  mongodb_data:
    driver: local

# Networks
networks:
  solveria-network:
    driver: bridge
